### ISSUE TITLE
2 specs failing

### ISSUE THREAD

**Issue by aew** [cutalion/grape-api-example#1]
When I clone and run the tests, I'm seeing the following (cryptic) failures from rspec:

 1) API::Accounts POST /v1/accounts should create an account
     Failure/Error: post "/v1/accounts", params.merge(api_key: partner.api_key)
     NoMethodError:
       undefined method `each' for true:TrueClass
     # ./spec/app/api/accounts_spec.rb:41:in`block (3 levels) in <top (required)>'

  2) API::Accounts GET /v1/accounts/:id should return account info
     Failure/Error: get "/v1/accounts/#{account.uuid}", api_key: partner.api_key
     NoMethodError:
       undefined method `each' for true:TrueClass
     # ./spec/app/api/accounts_spec.rb:11:in`block (3 levels) in <top (required)>'

Are you also seeing this?

Thanks!

**Comment by cutalion** [comment]
Hi Edward, 

I just cloned it and checked specs - all green. 
What's your environment?

Thanks,
Alex

**Comment by aew** [comment]
Hmm.  Thanks for checking.  I'm on Mac OSX.  After cloning, I changed the name of database.yml and created the databases, ran all of the commands, and then the tests and they are not passing.  Have tried with the following Ruby versions:
- ruby-1.9.3-p327 [ x86_64 ]
- ruby-1.9.3-p448 [ x86_64 ]
- ruby-2.0.0-p247 [ x86_64 ]
  I'm consistently seeing the errors...

**Comment by cutalion** [comment]
Odd. I've removed all gems, installed them again and tested against ruby 1.9.3 and 2.0. No errors.
Ubuntu 13.04, x64

Please, let me know if you find something.

**Comment by aew** [comment]
This is related to FDOC on my machine.  The error is actually coming from:
json-schema-2.1.1/lib/json-schema/attributes/required.rb:6:in `validate'
json-schema-2.1.1/lib/json-schema/validator.rb:95:in`block in validate'
json-schema-2.1.1/lib/json-schema/validator.rb:93:in `each'
json-schema-2.1.1/lib/json-schema/validator.rb:93:in`validate'
json-schema-2.1.1/lib/json-schema/schema.rb:38:in `validate'
json-schema-2.1.1/lib/json-schema/attributes/properties_v4.rb:15:in`block in validate'
json-schema-2.1.1/lib/json-schema/attributes/properties_v4.rb:6:in `each'
json-schema-2.1.1/lib/json-schema/attributes/properties_v4.rb:6:in`validate'
json-schema-2.1.1/lib/json-schema/validator.rb:95:in `block in validate'
json-schema-2.1.1/lib/json-schema/validator.rb:93:in`each'
json-schema-2.1.1/lib/json-schema/validator.rb:93:in `validate'
json-schema-2.1.1/lib/json-schema/schema.rb:38:in`validate'
json-schema-2.1.1/lib/json-schema/validator.rb:213:in `validate'
json-schema-2.1.1/lib/json-schema/validator.rb:374:in`validate!'
fdoc-0.3.0/lib/fdoc/endpoint.rb:19:in `consume_request'
fdoc-0.3.0/lib/fdoc/service.rb:38:in`verify!'
fdoc-0.3.0/lib/fdoc/spec_watcher.rb:21:in `check_response'
fdoc-0.3.0/lib/fdoc/spec_watcher.rb:13:in`block (2 levels) in module:SpecWatcher'
./spec/app/api/accounts_spec.rb:44:in `block (3 levels) in <top (required)>'

Looking at the line that fails: https://github.com/hoxworth/json-schema/blob/master/lib/json-schema/attributes/required.rb#L6

We can see that current_schema.schema['required'] is expected to return an array but instead is returning true.  Why this would be the case for me (mac) but not for you (linux) is not obvious.

**Comment by cutalion** [comment]
Thanks for investigation. I don't think it's related to linux. 
I have json-schema 2.0.3 in gemset. I'll try to update it tomorrow and run tests.

**Comment by cutalion** [comment]
Hm... no errors with json-schema 2.1.1
